on: push
jobs:
  device-endpoint-actions:
    strategy:
      matrix:
        devices: ['CC5A535FEA2F', '74860B8FDA23', '382056192034']
    name: Call Device Endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Download Current Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install and verify Node Modules
        run: |
            npm install
            npm list
        
      - name: Call Device Endpoint
        id: apiCall
        uses: 'DeclanRodgers/XAPI-Github-Action@1.0b'
        with:
             destination-filter: ${{ matrix.devices }}
             token-data: ${{ secrets.JWT_TOKEN }}
             