on: push
jobs:
  device-endpoint-actions:
    name: Call Device Endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Download Current Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install and verify Node Modules
        run: |
            npm install
            npm list

     # - name: Install and verify Node Modules
      #  run: |
       #     npm install -g axios@1.3.4 
        #    npm list axios
        
      - name: Call Device Endpoint
        id: apiCall
        uses: 'DeclanRodgers/XAPI-Github-Action@0.9'
        with:
             destination-filter: 'CC5A535FEA2F'
             token-data: ${{ secrets.JWT_TOKEN }}
             